export const galleryData = [
  {
    id: 1,
    category: "Swedish Massage",
    title: "Relaxing Swedish Massage Session",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 2,
    category: "Swedish Massage",
    title: "Peaceful Treatment Room",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 3,
    category: "Swedish Massage",
    title: "Aromatherapy Enhancement",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 4,
    category: "Deep Tissue",
    title: "Deep Tissue Therapy Session",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 5,
    category: "Deep Tissue",
    title: "Muscle Tension Relief",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 6,
    category: "Deep Tissue",
    title: "Professional Technique",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 7,
    category: "Cupping Therapy",
    title: "Traditional Cupping Treatment",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 8,
    category: "Cupping Therapy",
    title: "Ancient Healing Method",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 9,
    category: "Cupping Therapy",
    title: "Therapeutic Cup Placement",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 10,
    category: "Sound Healing",
    title: "Sound Bowl Therapy",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 11,
    category: "Sound Healing",
    title: "Meditation and Sound",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 12,
    category: "Sound Healing",
    title: "Vibrational Healing",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 13,
    category: "Sports Massage",
    title: "Athletic Recovery Session",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 14,
    category: "Sports Massage",
    title: "Performance Enhancement",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 15,
    category: "Sports Massage",
    title: "Muscle Recovery Treatment",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 16,
    category: "Baby Massage",
    title: "Gentle Baby Massage",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 17,
    category: "Baby Massage",
    title: "Parent-Child Bonding",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 18,
    category: "Baby Massage",
    title: "Infant Relaxation",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 19,
    category: "Injury Recovery",
    title: "Rehabilitation Session",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 20,
    category: "Injury Recovery",
    title: "Joint Mobility Treatment",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 21,
    category: "Injury Recovery",
    title: "Recovery Therapy",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 22,
    category: "Facility",
    title: "Reception Area",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 23,
    category: "Facility",
    title: "Treatment Room",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 24,
    category: "Facility",
    title: "Relaxation Space",
    image: "/placeholder.svg?height=400&width=600",
  },
]

export const categories = [
  "All",
  "Swedish Massage",
  "Deep Tissue",
  "Cupping Therapy",
  "Sound Healing",
  "Sports Massage",
  "Baby Massage",
  "Injury Recovery",
  "Facility",
]
